export { default as Favorites } from "./Favorites";
export { default as Footer } from "./Footer";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Content } from "./Content";
export { default as Featured } from "./Featured";
export { default as Head } from "./Head";
export { default as Main } from "./Main";
export { default as Cards } from "./Cards";